### ISSUE TITLE
directory separator

### ISSUE THREAD

**Issue by FranckFreiburger** [jyu213/ssh2-sftp-client#104]
Directory separator should be platform agnostic:
https://github.com/jyu213/ssh2-sftp-client/blob/7fac3beb69d5128cc0a3577f2afecd92e6964cba/src/index.js#L8

should be replaced with:
```
const osPath = require('path').posix;
```
(see https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-6)

see PR #105

**Comment by jyu213** [comment]
publisher new version
