### ISSUE TITLE
connect() hangs if stream ends before SFTP ready

### ISSUE THREAD

**Issue by rkaw92** [jyu213/ssh2-sftp-client#109]
Normally, one expects `SFTPClient.connect` to either connect or fail (reject) after a given time. However, it could happen that the connection closes between establishing the actual SSH channel and getting an SFTP subsystem. Indeed, given the following sequence of events, we get a "hung Promise" that never fulfills or rejects:
1. call `SFTPClient.connect`
2. the underlying SSH client connects and emits `ready`
3. the connection is broken (for example by TCP RST) - the client emits `end`, but no `error` (!)
4. the promise returned from `SFTPClient.connect` (1) is now hung, as it will never reject (because we got no error)

It would be best to also listen for `SSHClient` event `end` as long as we're connecting and reject as if we got an error.

**Comment by jyu213** [comment]
thanks for pr. and merged
