### ISSUE TITLE
recursive mkdir gets stucked 

### ISSUE THREAD

**Issue by petersimun** [jyu213/ssh2-sftp-client#114]
When creating new directory using mkdir("/", true), method never ends and loops infinitelly

  let mkdir = p => {
      let {dir} = osPath.parse(p);
      return this.exists(dir).then((type) => {
        if (!type) {
          return mkdir(dir);
        }
      }).then(() => {
        return doMkdir(p);
      });
  };

problem si with this.exists("/") which returns false and routine iterated till forever.

**Comment by theophilusx** [comment]
Looks like this issue could be closed?

**Comment by zjgdbansd** [comment]
Tried doing a recursive mkdir, hangs indefinitely. Still an issue.

**Comment by sor-barroso** [comment]
:up:

**Comment by theryaz** [comment]
I had this issue too, I created https://github.com/jyu213/ssh2-sftp-client/pull/146
