### ISSUE TITLE
File not uploading to the SFTP server

### ISSUE THREAD

**Issue by talbotlawrence** [jyu213/ssh2-sftp-client#12]
I have a question not an issue--big thanks up front:

I'm trying to use your "put" method, but the file is not being sent to the server.  I'm not getting any error messages.  Would this code work below?  By the way, the sftp.list method is working!

![image](https://cloud.githubusercontent.com/assets/456527/23872899/0c0a6536-07fe-11e7-8284-0a070b190096.png)

**Comment by talbotlawrence** [comment]
Nevermind!  I got it to work using the zlib compression below--thank you for your code:
sftp.put("/home/user/sftp/file.txt", "/upload/file.txt", "zlib");

**Comment by jyu213** [comment]
@talbotlawrence thanks for your advice

**Comment by yiochen** [comment]
For anyone got the same problem and stumbled upon this issue. The real problem is not the compression.
`sftp.put('/home/user/sftp/file.txt', '/upload/file.txt')` returns a promise, in order to wait for it to resolve, we need to return it
```
.then(() => {
   return sftp.put('/home/user/sftp/file.txt', '/upload/file.txt');
}).then(() => {
   return sftp.list('/upload');
})
```
