### ISSUE TITLE
append Over Writes file

### ISSUE THREAD

**Issue by vorticalbox** [jyu213/ssh2-sftp-client#135]
When append to a file it gets over written by the last append that was called.

```
const Client = require('ssh2-sftp-client');
const sftp = new Client();
await sftp.put(Buffer.from('hello'), 'test.txt`);
await sftp.append(Buffer.from('world'), 'test.txt`);
```

the file after will just contain "world"

**Comment by vorticalbox** [comment]
After reading the ss2 and ssh2 streams documention you can chnage the mode to append 

```
await sftp.append(Buffer.from('world\n'), 'test.txt`, { flags: 'a' });
```

**Comment by theophilusx** [comment]
Based on the information you provided, my guess is that the operation
your trying to do is not supported by the remote sftp server your
interacting with. 

You have completely failed to provide even the most minimal information
necessary to provide any assistance. If you cannot be bothered putting
in any effort in reporting an issue, I certainly cannot be bothered
trying to assist.

**Comment by huriza-tr** [comment]
@theophilusx  I am creating a CSV file on a FTP server. Its successfully executing the function when I create a file and write onto it but I want to send my data to that file at regular intervals so I want to append data at the end of the file, but it overwrites it. And when I set { wrtieStreamOptions: { flags: 'a' } }. It simply throws this one line error
`put: Requested operation is not supported. /test/testfile.csv`
and the same for append method
`append: Requested operation is not supported. /test/testfile.csv`
This is my line of code:
`sftpClient.put(this.asyncParser.processor, directory, { wrtieStreamOptions: { flags: 'a' } });`
I am sorry for previous comment and please tell me how can I configure my server to allow me to append to it, Though I have permission to write.
