### ISSUE TITLE
Preserve timestamps

### ISSUE THREAD

**Issue by mikes-gh** [jyu213/ssh2-sftp-client#15]
Can timestamps be preserved when doing a put?
Same as -p option in linux sftp client

```
sftp> put -p test.html test.html
```

See https://github.com/mkloubert/vs-deploy/issues/60

**Comment by jyu213** [comment]
@mikes-gh , apologize deeply for the delayed reply. 
`sftp.put` doesn't support options like -p. 
It will be create a method like `sftp.utimes()` if you like

**Comment by zNoobs** [comment]
I don't see any sftp.utimes() function, how can I do to preserve the modified time of my file?

**Comment by theophilusx** [comment]
Currently, this is not supported by the library. This could be added,
but right now I don't have time to implement. A PR with associated test
cases would certainly be considered.

The ssh2-streams module has a utimes() method, so to add this
functionality, all that is really required is a Promise which wraps
around the utimes() call, resolves if no error and rejected if the
callback has the error arg set. If you look at other methods, you will
see the basic pattern.

**Comment by zNoobs** [comment]
Thanks for the answer, I edited my previous comment I don't think you saw it.
Do you know why the utimes() function doesn't set the same value as my parameters? 
By example if I set 1611334757000, it will set 722021000000.

**Comment by zNoobs** [comment]
The timestamp should be in seconds and not milliseconds!
