### ISSUE TITLE
Need to be able to control the encoding of stream

### ISSUE THREAD

**Issue by siparsons** [jyu213/ssh2-sftp-client#16]
There was a change that introduced the ability to control the encoding used when retrieving a readable stream for ftp.get but it has since been reverted by @jyu213 in revision #9 , which is a shame, because when using this library to download zip files from an SFTP server binary encoding is the only encoding method that works (not utf8 which is the default). 

Any chance that this change can be reinstated?

**Comment by txssseal** [comment]
👍  for this.  I need to be able to encode as binary as well.

**Comment by jyu213** [comment]
@siparsons @txssseal  publish a new version 1.1.0 to support the problem.
I was misunderstood Teppo Kauppinen's PR for a long time. 
Thank you.
