### ISSUE TITLE
Release a new (minor?) version

### ISSUE THREAD

**Issue by matthew-andrews** [jyu213/ssh2-sftp-client#18]
Hi there, thank you for this library it's really useful.

We've been using it to download some binary files and discovered that to stop the files being corrupted en-route we need this change:-
https://github.com/jyu213/ssh2-sftp-client/pull/17

Right now we've hard coded our `package.json` to point to that exact commit but would it be possible for it to be released as a new version on NPM?

Many thanks again!

Matt

**Comment by jyu213** [comment]
@matthew-andrews  Hi, publish a new Version1.1.0 to resolve the problem.

**Comment by matthew-andrews** [comment]
谢谢你啊！
