### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by codeKk21** [jyu213/ssh2-sftp-client#21]
let Client = require('ssh2-sftp-client');
let sftp = new Client();
sftp.connect({
    host: '*.*.*.*',
    port: '22',
    username: '*********',
    password: '*****'
}).then(() => {
	console.log("working");
    return sftp.list('');
}).then((data) => {
    console.log(data, 'the data info');
}).catch((err) => {
    console.log(err, 'catch error');
});

Above is the code I am using to connect my sftp server built on Cerberus with password and username  but the error is :- 
{ Error: All configured authentication methods failed
    at tryNextAuth (/home/kundan/medley-inv/node_modules/ssh2-sftp-client/node_modules/ssh2/lib/client.js:294:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/kundan/medley-inv/node_modules/ssh2-sftp-client/node_modules/ssh2/lib/client.js:473:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:192:7)
    at parsePacket (/home/kundan/medley-inv/node_modules/ssh2-sftp-client/node_modules/ssh2-streams/lib/ssh.js:3647:10)
    at SSH2Stream._transform (/home/kundan/medley-inv/node_modules/ssh2-sftp-client/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/kundan/medley-inv/node_modules/ssh2-sftp-client/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12) level: 'client-authentication' } 'catch error'

**Comment by Xsmael** [comment]
'am experiencing the same issue !   any solution ?

**Comment by shishir99111** [comment]
facing the same issue

for the configuration:
`
try{
 sftp.connect({
      host: '111.111.11.111',
      port: 22,
      username: '*********',
      password: '*********',
 })
}catch(e){
 throw(e)
}
`
giving error: 
`All configured authentication methods failed`

**Comment by Xsmael** [comment]
Any solution for this  ?

**Comment by jyu213** [comment]
@codeKk21 , @Xsmael 
will this issue helps? 
https://github.com/mscdex/ssh2/issues/604

**Comment by ddduarte** [comment]
I solved using `tryKeyboard = true` configutation on connect and 

`    
   this.ftpClient['client'].on('keyboard-interactive', (name, instructions, instructionsLang, prompts, finish) => {
        finish([this.ftpConfig.connection.password]);
    }); `

**Comment by sauraCactus** [comment]
Hi guys, what is the workaround right now? I don't know where am I supposed to place the this.ftpClient ... that @ddduarte shared.

Thanks in advance guys.

**Comment by theophilusx** [comment]
There is no 'workaround' necessary. This error typically indicates the remote SFTP server supports either key exchange or ciphers which are not enab led by default in SSH2. The solution is to set the authentication property of the configuration object appropriately. See the SSH2 documentation for connect() and available options.

**Comment by MrHIDEn** [comment]
Something is wrong with this library.
1) I got the same error with this library.
2) I did test with 'sftp-async' and I got connection and files... and all works with the same 'config'.

**Comment by theophilusx** [comment]
What version of ssh2-sftp-client?

What version of node?

What platform is node running on?

This error is usually due to the remote server not supporting any of the
default key exchange or cipher algorithms. See the algorithm property of
the connect options in the ssh2 documentation (make sure it is the 0.8.x
version, not the new 1.x version of ssh2) to see how you can add
additional key exchange and cipher algorithms. You can use something
like openSSH's sftp CLI with the verbose flag to see what algorithm is
being used by the remote server.

If you still cannot get it to work, you need to provide a minimal
script which reproduces the problem in order for me to reproduce the
issue and debug it.
