### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by omkartin** [jyu213/ssh2-sftp-client#31]
I am getting the following error, please help:

{ Error: Timed out while waiting for handshake at Timeout._onTimeout (node_modules/ssh2/lib/client.js:569:19) at ontimeout (timers.js:386:14) at tryOnTimeout (timers.js:250:5) at Timer.listOnTimeout (timers.js:214:5) level: 'client-timeout' } 'catch error'

**Comment by jyu213** [comment]
issues:  https://github.com/mscdex/ssh2/issues/393
