### ISSUE TITLE
Document the need to end the connection

### ISSUE THREAD

**Issue by tdmalone** [jyu213/ssh2-sftp-client#42]
Hi there,

Thank you for this wrapper - it works well!

One thing that did catch me out when following the examples was that the connection stayed open. I searched for methods such as 'disconnect' to close it, and eventually found the `.end()` method in the [ssh2](https://github.com/mscdex/ssh2) docs. Would it be worth documenting this here too, particularly alongside the main usage example in the README?

EDIT: I would open a pull request for it myself, I'm just not sure if one should put `sftp.end()` both in within the final `.then()` or in the `.catch()` as well?

**Comment by jyu213** [comment]
@tdmalone , thanks for your working. It's worked both `then()` and `catch()`

**Comment by HnLn** [comment]
Agreed, should be documented, my lambda function had timeouts because the connection stayed open.

**Comment by jyu213** [comment]
Tks all, updated it documents.
