### ISSUE TITLE
[Solved] SFTP : Key + Password

### ISSUE THREAD

**Issue by nitingautam** [jyu213/ssh2-sftp-client#44]
How to authenticate with key + password for a SFTP server?

**Comment by nitingautam** [comment]
Below is my code....i tested it work fine if i use either key or password but not working for both

let Client = require('ssh2-sftp-client');
let sftp = new Client();
sftp.connect({
    host: '104.197.5.23',
    port: '22',
    username: 'nits',
    privateKey: require('fs').readFileSync('id_rsa'),
    password: 'test'
}).then(() => {
    return sftp.list('/home/nitingautam_usa');
}).then((data) => {
    console.log(data, 'the data info');
}).catch((err) => {
    console.log(err, 'catch error');
});

**Comment by nitingautam** [comment]
{ Error: All configured authentication methods failed
 
    at doWrite (_stream_writable.js:334:12) level: 'client-authentication' } 'catch error'

**Comment by jyu213** [comment]
https://github.com/mscdex/ssh2#user-content-client-methodsl

**Comment by andershal** [comment]
Use _passphrase_ instead of _password_.

**Comment by nitingautam** [comment]
Able to fix this with AUthmethods  sequence should be Password, publickey
