### ISSUE TITLE
Set modes on files

### ISSUE THREAD

**Issue by pyrsmk** [jyu213/ssh2-sftp-client#5]
Hi,

Do you think it could be possible to set modes on remote files? I'm working on a gulp script with FTP/SFTP deployment and `gulp-sftp` is kinda outdated so I'm considering using this library instead ^^

Cheers!

**Comment by jyu213** [comment]
most of the time, we don't need to reset the file type. the user has his own permission. 
also, ssh2-sftp-client support reset file modes like `sftp.put(path, {mode: 0o666})` if user has permission.

**Comment by pyrsmk** [comment]
Oops, this one was a bit old. I finally managed to create my SFTP adapter on top of ssh2 to fit my needs.
