### ISSUE TITLE
unable to built connection to a remote sftp when i run code on heroku enviorment.

### ISSUE THREAD

**Issue by vishavjeet** [jyu213/ssh2-sftp-client#55]
hi, from last 5-6 days my code stopped working on Heroku environment. but working fine on my local Linux server development. it is showing the following error. 

DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'
DEBUG: Client: Trying 205.211.164.97 on port 24 ...
DEBUG: Client: Connected
{ Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/app/node_modules/ssh2/lib/client.js:687:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) level: 'client-timeout' }

**Comment by jyu213** [comment]
is package V2.0.1 still woking on Heroku environment?

**Comment by vishavjeet** [comment]
no, it is not working. they use the different file system (ephemeral filesystem). so can not generate keys on there dyno and store like typical Linux server. but it was working before the update. I am exactly sure where the shortfall is. any help would be much appreciated.

**Comment by jyu213** [comment]
Feeling powerless about this☹️, you may ask for help at https://github.com/mscdex/ssh2/issues

**Comment by vishavjeet** [comment]
yea I think I am gonna have to do it. but thanks for try to help.
