### ISSUE TITLE
New method fileExists

### ISSUE THREAD

**Issue by joh-klein** [jyu213/ssh2-sftp-client#56]
I occasionally have to check in a large remote dir (4000+ files) if a specific file exists. Don't even need to download it. Is there a quicker way then listing the whole dir and Array.forEach()?

**Comment by jyu213** [comment]
`sftp.isExist` method is not provided yet.
You also can use ssh2's `readdir` method to reduce once cycle.
More effective processing is execute a remote command, just like package [ssh2](https://github.com/mscdex/ssh2) `ssh.exec('find /path -type d 2>/dev/null')`

**Comment by jyu213** [comment]
ssh2-sftp-client currently focus only on the sftp client.
ssh method is also good, but support it also need lot work to do.

**Comment by joh-klein** [comment]
#67 could be a way to implement this functionality!

**Comment by theophilusx** [comment]
As the mdoule now has a method for testing for the existence of a file, this issue can either be closed or have the title changed to better reflect the required functionality?
