### ISSUE TITLE
Encoding when putting files

### ISSUE THREAD

**Issue by cenkozan** [jyu213/ssh2-sftp-client#61]
First of all, thank you so much for this package.

I have an issue I am trying to solve. Some software can not read my files, so I want to try changing the encoding and try again.

Readme says 'put' supports encoding, but the method signature goes directly into callback instead of encoding, right after the compression.

Can you please update the documentation or is there something else that I should do, please.

Thank you very much.

**Comment by jyu213** [comment]
it's just like method `get`. you can set encoding in third options. I will update documents later. 

Thanks for your advice.
