### ISSUE TITLE
sftp.get is missing a chunk

### ISSUE THREAD

**Issue by yonguelink** [jyu213/ssh2-sftp-client#63]
We're using this lib to get a few files from our SFTP server.

As of v2.2.0, the `sftp.get` method doesn't seems to work as intended.

After looking around, I came across the following commit: https://github.com/jyu213/ssh2-sftp-client/commit/08b96f1eebd8610459705186c37d40a5389eafb7

Calling `stream.read()` will *remove* a chunk of the buffer. Once you return the stream, a chunk is missing.

**Comment by jyu213** [comment]
sorry, there's some mistake with  the new version 2.2.0

**Comment by akdixit1** [comment]
Hi @jyu213, can we expect a fix for this issue soon ??

**Comment by yonguelink** [comment]
@akdixit1 If it's too much of an issue for you, you can:

1. Fix your working version to something prior to 2.2.0 (i.e.: 2.1.1)
2. Fork this repo and revert the commit I linked in my first comment (08b96f1)

@jyu213 marked v2.2.0 as 'deprecated' on NPM, so there's that. I'm pretty sure we'll get a fix soon enough!

**Comment by jyu213** [comment]
Can't find the resolve of `readable` and `data` event bind on V10.0.0, so I reset with version V2.2.1,
and publish a new version V3.0.0 to change `sftp.get` to return a chunk instead of stream.

**Comment by yonguelink** [comment]
@jyu213 
Hum, what if what we want to fetch doesn't fit in the chunk? (i.e.: relatively large file (~4mb)). I'm not sure how you could work around that (as I'm not familiar with the changes in Node 10) tho...

the v2.2.1 is good tho, thanks for that!

**Comment by thomasInes** [comment]
@yonguelink if `sftp.get` returns a chunk now, how can we get all the chunks for a big file for exemple.
Could you kindly provide a code?
Thank you

**Comment by jyu213** [comment]
emm.. big chunnks is also a trouble..

**Comment by yonguelink** [comment]
@thomasInes I wouldn't upgrade to v3.0.0 and keep using the stream from v2.2.1

@jyu213 I'm not sure if it's something you can do, but what about doing nothing for that Node 10? It's the `stream` contract that changed apparently, those using the stream should adapt to it, not you that is "simply" providing the stream.

I'm also reading the doc for the stream data event (https://nodejs.org/api/stream.html#stream_event_data) and found:

> The **'data' event is emitted** whenever the stream is relinquishing ownership of a chunk of data to a consumer. This may occur **whenever the stream is switched in flowing mode by calling readable.pipe(), readable.resume(), or by attaching a listener callback to the 'data' event**. The 'data' event will also be emitted whenever the readable.read() method is called and a chunk of data is available to be returned.

My guess here is that anyone having trouble with the stream should probably be using `.pipe`. Also the lib `mississippi2` provides lots of very helpful methods around streams.

**Comment by yonguelink** [comment]
I don't know if I'm misunderstanding something, but why does `sftp.get` returns a promise?

I went and tried with Node v10 with the following modified `.get` method:

```js
SftpClient.prototype.get = function(path, useCompression, encoding) {
  let options = this.getOptions(useCompression, encoding)
  let sftp = this.sftp;
  if (sftp) {
    return sftp.createReadStream(path, options);
  }
};
```

Along with a calling method:


```js
const SFTP = require('ssh2-sftp-client');
const path = require('path');

function download (sftp, dir, fileName) {
  const stream = sftp.get(path.join(dir, fileName), true, 'utf8');
  return new Promise((resolve, reject) => {
    stream.on('error', err => reject(err));
    stream.on('end', () => {
      sftp.end();
    });
    stream.pipe(concatStream(res => resolve(res)));
  });
}

async function connect (host, port) {
  const sftp = await new SFTP();
  await sftp.connect({
    host: host,
    port: port,
    username: process.env.SFTP_USERNAME,
    password: process.env.SFTP_PASSWORD
  });

  return sftp;
}

connect(host, port)
  .then(sftp => {
    const rawDump = await download(sftp, '/some/path/to/my/large/file', 'myLargeFile.txt');
    // Do whatever with your "rawDump"
  })
  .catch(console.error);
```

All this effectively download the file on Node v10 :)

**Comment by jyu213** [comment]
It's designed for chained call at the beginning, so you don't have to use promise in `get`, but it seems like not good enough. 
And I decide to and other method if need, just like [`fastGet`](https://github.com/jyu213/ssh2-sftp-client/pull/64/commits/468ed4a5ed6561524f3788f72e371a1f2811e7f9).
