### ISSUE TITLE
Not receiving error callback if underlying SSH connection disconnected

### ISSUE THREAD

**Issue by ochimo** [jyu213/ssh2-sftp-client#65]
I am finding that callbacks are not being invoked when the underlying SSH connection has been disconnected - and in these cases the Promise never completes and hangs.  

Specific example, making call to SftpClient.delete(path) - it calls the underlying ssh2-streams unlink call as (line 256):
 ```
     sftp.unlink(path, (err) => {
                if (err) {
                    reject(err);
                    return false;
                }
                resolve();
            });
```
Now if the call fails because of a response from the server like "file not found" then the callback is called from unlink and reject is called properly.

However, if you configure the OpenSSH server to timeout for inactivity and break before issuing the sftp.unlink call, then the underlying SSH connection is terminated by the server before we call unlink.  When we call sftp.unlink, when attempting to write the SFTP command to the SSH channel an EPIPE error is generated.  This is NOT passed back to the callback above by ssh2-streams module.    Instead we can catch it using .on("error") and rejecting, but there is not code to handle this case in the ssh2-sftp-client library.

As an aside in this case there is an .on("error") listener that is called -- it is the one that was set in SftpClient.connect line 317, but that is out of scope and calls the wrong reject :)

The result of this is that if you call SftpClient.delete (& other commands link rename, etc.) and the error is because the SSH connection is dead, then the call hangs because you never get a reject or resolve because ssh2-sftp-client library never gets a callback.

I have worked around this by adding an .on("error") for unlink to catch the EPIPE message and reject -- but this seems like an issue that would impact most of the other methods in this library.

What am I missing? :)

**Comment by rares** [comment]
+1, I have experienced similar behavior.
