### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by uxsoft** [jyu213/ssh2-sftp-client#7]
Is there a way to use this with http proxy?

**Comment by FaberNa** [comment]
Is there a way to use with proxy ?

**Comment by FaberNa** [comment]
` sftp.connect(se).then(
        function(){
            return sftp.list(se.remotePath);
        }).then(
            function(data){
            console.log(data, 'the data info');
            }
        ).then(
            function(error){
                console.log(err, 'catch error');
            }
        )`
It' possible to say at connection don't ignore prozy ( like filezilla properties )
