### ISSUE TITLE
Upgrade ssh2 dependency to 0.6.1

### ISSUE THREAD

**Issue by richardlay** [jyu213/ssh2-sftp-client#82]
Node 10 has introduced a breaking change where I get an `Unknown message digest` error when using the `ssh-dss` algorithm. 

It looks like it was fixed in https://github.com/mscdex/ssh2-streams/issues/101

Can we update the `ssh2` dependency to `0.6.1`?

**Comment by jyu213** [comment]
upgrade version to 3.1.0.
also, `ssh2-sftp-client` has `get` chunk unresolved
