### ISSUE TITLE
Request for stream support

### ISSUE THREAD

**Issue by adam-nielsen** [jyu213/ssh2-sftp-client#90]
I'd like to request support for streams, so that we can download files via SFTP and pass them to other stream consumers with `pipe()`.

I have been able to do this in an unofficial way like this, but it would be nice if there were a first-class function that could do this, like `getStream()` for example:
```
let sftp = new ...
await sftp.connect(...
const stream = sftp.sftp.createReadStream('filename', {encoding: null});
stream.pipe(fs.createWriteStream('out.dat'));
```
My use case is to download a file via SFTP and upload it to Amazon S3, so being able to do that with streams so that I don't need to store any data locally would be very useful.

**Comment by joelharkes** [comment]
ah same issue here thanks for the fix :)

**Comment by ryansmith94** [comment]
Yeah having this issue too.

**Comment by joelharkes** [comment]
@Crazometer  i think this might have been fixed here: 
https://github.com/jyu213/ssh2-sftp-client/commit/4a66d255b37091a8d7378bfbcd8c27af3ebdc745

Back when i tried this, it didn't work.

**Comment by adam-nielsen** [comment]
Not sure exactly but it certainly looks like the `get()` call will now do what we need, so I'm going to close this as resolved.

**Comment by joelharkes** [comment]
There is a weird order in versioning:
I use 3.1.0
but the latest uploaded version seems to be: 2.4.3. so im not sure if 3.1.0 is a mistake or abandoned?

**Comment by rkaw92** [comment]
Joël, as a fellow user I can confirm something went quite wrong with this package's versioning. Indeed, the stream/promise API did change between versions, and 3.x seems to be vaporware.

Dnia 2 stycznia 2019 15:15:49 CET, "Joël Harkes" <notifications@github.com> napisał(a):

**Comment by joelharkes** [comment]
my advice, use 2.4.3

although pumping/piping the create stream still doesn't work in that version somehow (for me).

keep using:
```
sftp.sftp.createReadStream('filename', {encoding: 'utf-8'});
```
