### ISSUE TITLE
Using Async Await On .connect() Cause Error

### ISSUE THREAD

**Issue by JonnyBoy333** [jyu213/ssh2-sftp-client#92]
Not sure why but when I call the .connect method and chain the promise everything works fine but when I call await .connect() inside of an async function I get an error.

Working:
```
const sftp = new Client();
sftp.connect({
  host: 'xx.xx.xx.xx',
  port: 22,
  username: 'username',
  password: 'password',
  algorithms: { serverHostKey: ['ssh-rsa', 'ssh-dss'] }
})
.then(() => {
  return sftp.list('/path/to/files');
}).then((data) => {
  console.log(data, 'the data info');
}).catch((err) => {
  console.log(err, 'catch error');
});
```

Not Working:
```
const sftp = new Client();
await sftp.connect({
  host: 'xx.xx.xx.xx',
  port: 22,
  username: 'username',
  passphrase: 'password',
  algorithms: { serverHostKey: [ 'ssh-rsa', 'ssh-dss' ] }
});
const list = await sftp.list('/path/to/files');
console.log('Directory Info', list);
```

This causes this error: `Error: All configured authentication methods failed`

**Comment by JonnyBoy333** [comment]
Figured out a good way to do this like so:
```
const sftp = await connect(addressInfo.address, username, password);
const folders = await sftp.list(root);

async function connect(host, username, password) {
  const sftp = await new Client();
  await sftp.connect({ host, port: 22, username, password, algorithms: { serverHostKey: ['ssh-rsa', 'ssh-dss'] } });
  return sftp;
}
```

**Comment by ads6495** [comment]
Hi,

i am trying something very familiar in my app and i used 
`const sftp = await connect(addressInfo.address, username, password);
const folders = await sftp.list(root)`

in a similar way but i get a syntaxError "await is only valid in async function"

**Comment by theophilusx** [comment]
Is that call inside a function which is declared with async?

There is nothing in the module that would cause this error. It has to be
an issue in your code.


-- 
Tim Cross

**Comment by dylanatimdex** [comment]
I have the same issue
